### ISSUE TITLE
Namespaces in XPath don't work

### ISSUE THREAD

**Issue by charlie430** [xorets/ObjectXPathNavigator#3]
I can't seem to get namespaces to work when executing an xpath. Is that supposed to work?

```
    // Generate simple objects
    var objects = new List<SimpleObject>();
    for (var i = 0; i < 3; i++) {
        var o = new SimpleObject {
            Attr2 = i.ToString(CultureInfo.InvariantCulture),
            Elem1 = "Elem1" + i,
            Elem2 = "Elem2" + i
        };
        objects.Add(o);
    }

    // Create navigator
    var context = new ObjectXPathContext();
    context.NamespaceManager.AddNamespace("sdf", Namespaces.SDF);
    var nav = (ObjectXPathNavigator)context.CreateNavigator(objects);

    // Select nodes
    //var nodes = nav.SelectObjects("//*[2]");
    var nodes = nav.SelectObjects("//sdf:child2");
    Assert.AreNotEqual(0, nodes.Length);
    Assert.AreEqual("Elem20", nodes[0]);
```

I get this error after calling SelectObjects.
System.Xml.XPath.XPathException : Namespace Manager or XsltContext needed. This query has a prefix, variable, or user-defined function.
   at System.Xml.XPath.XPathNavigator.Evaluate(XPathExpression expr, XPathNodeIterator context)
   at System.Xml.XPath.XPathNavigator.Select(XPathExpression expr)

Any ideas on how to fix this? I am adding the appropriate namespaces to the XmlNamespaceManager so I don't know why this doesn't work.

**Comment by charlie430** [comment]
Looks like you just need to make it possible to pass in an IXmlNamespaceResolver to SelectObject and SelectObjects.

**Comment by xorets** [comment]
You are right, if we need to use namespace in an XPath query, then we need to map prefix to a namespace with IXmlNamespaceResolver. As ordinal XPathNavigator.Select() method does. Namespace manager in ObjectXPathContext looks like it is related, but it doesn't. 

Frankly, I never used those SelectObject methods by myself, that's why it lacks this functionality. Do you need this implemented?

**Comment by charlie430** [comment]
I can just use the regular Select method if you don't implement it. It would be helpful to be able to use the IXmlNamespaceResolver, though. I am using the ObjectXPathNavigator as a way to apply styles to a C# object graph. My clients express their styles in CSS syntax. To apply the styles I convert them to XPath using css2xpath (https://bitbucket.org/MostThingsWeb/css2xpath), and using ObjectXPathNavigator I can find the objects in the object graph, and then apply the changes.

**Comment by xorets** [comment]
Added optional nsResolver parameter to those methods. Please try.
